// front-react/src/components/UserForm.js
import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { getUser, createUser, updateUser } from '../services/userService';

const UserForm = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [user, setUser] = useState({ name: '', email: '', password: '', username: '' });

  useEffect(() => {
    if (id) {
      fetchUser(id);
    }
  }, [id]);

  const fetchUser = async (id) => {
    const response = await getUser(id);
    setUser(response.data);
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setUser({ ...user, [name]: value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (id) {
      await updateUser(id, user);
    } else {
      await createUser(user);
    }
    navigate('/');
  };

  return (
    <div>
      <h2>{id ? 'Edit User' : 'Add User'}</h2>
      <form onSubmit={handleSubmit}>
        <div>
          <label>Name:</label>
          <input type="text" name="name" value={user.name} onChange={handleChange} required />
        </div>
        <div>
          <label>Email:</label>
          <input type="email" name="email" value={user.email} onChange={handleChange} required />
        </div>
        <div>
          <label>Password:</label>
          <input type="password" name="password" value={user.password} onChange={handleChange} required />
        </div>
        <div>
          <label>Username:</label>
          <input type="text" name="username" value={user.username} onChange={handleChange} required />
        </div>
        <button type="submit">{id ? 'Update' : 'Create'}</button>
      </form>
    </div>
  );
};

export default UserForm;

// front-angular-reactive/src/app/users/user-form/user-form.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';
import { UserService } from '../user.service';
import { User } from '../user.model';

@Component({
  selector: 'app-user-form',
  templateUrl: './user-form.component.html',
  styleUrls: ['./user-form.component.css']
})
export class UserFormComponent implements OnInit {
  userForm: FormGroup;
  userId: string | null = null; // Define la propiedad userId

  constructor(
    private fb: FormBuilder,
    private route: ActivatedRoute,
    private router: Router,
    private userService: UserService
  ) {
    this.userForm = this.fb.group({
      name: ['', Validators.required],
      email: ['', [Validators.required, Validators.email]],
      password: ['', Validators.required],
      username: ['', Validators.required]
    });
  }

  ngOnInit(): void {
    this.userId = this.route.snapshot.paramMap.get('id'); // Asegúrate de que userId sea string o null
    if (this.userId) {
      this.userService.getUser(this.userId).subscribe(data => {
        this.userForm.patchValue(data);
      });
    }
  }

  onSubmit(): void {
    console.log("es clicki",this.userForm.valid)
    if (this.userForm.valid) {
      const user: User = this.userForm.value;
      if (this.userId) {
        this.userService.updateUser(this.userId, user).subscribe(() => {
          this.router.navigate(['/users']);
        });
      } else {
        this.userService.createUser(user).subscribe(() => {
          this.router.navigate(['/users']);
        });
      }
    }
  }
}

<div>
    <h2>{{ userId ? 'Edit' : 'Add' }} User</h2> <!-- userId está definido -->
    <form [formGroup]="userForm" (ngSubmit)="onSubmit()"> <!-- userForm está definido, onSubmit también -->
      <div>
        <label for="name">Name</label>
        <input id="name" formControlName="name" />
      </div>
      <div>
        <label for="email">Email</label>
        <input id="email" formControlName="email" />
      </div>
      <div>
        <label for="password">Password</label>
        <input id="password" formControlName="password" type="password" />
      </div>
      <div>
        <label for="username">Username</label>
        <input id="username" formControlName="username" />
      </div>
      <div>
        <button type="submit">Save</button>
        <a [routerLink]="['/users']">Cancel</a>
      </div>
    </form>
  </div>
