// front-react/src/components/UserList.js
import React, { useEffect, useState } from 'react';
import { getUsers, deleteUser } from '../services/userService';
import { Link } from 'react-router-dom';

const UserList = () => {
  const [users, setUsers] = useState([]);

  useEffect(() => {
    fetchUsers();
  }, []);

  const fetchUsers = async () => {
    const response = await getUsers();
    setUsers(response.data);
  };

  const handleDelete = async (id) => {
    await deleteUser(id);
    fetchUsers();
  };

  return (
    <div>
      <h2>User List</h2>
      <Link to="/add">Add User</Link>
      <ul>
        {users.map(user => (
          <li key={user._id}>
            {user.name} - {user.email}
            <Link to={`/edit/${user._id}`}>Edit</Link>
            <button onClick={() => handleDelete(user._id)}>Delete</button>
          </li>
        ))}
      </ul>
    </div>
  );
};

export default UserList;

// front-angular/src/app/components/user-list/user-list.component.ts
import { Component, OnInit } from '@angular/core';

import { UserService } from '../../services/user.service';

@Component({
  selector: 'app-user-list',
  templateUrl: './user-list.component.html',
  styleUrl: './user-list.component.css'
})
export class UserListComponent implements OnInit {

  users: any = [];

  constructor(private userService: UserService) { }

  ngOnInit(): void {
    this.userService.getUsers().subscribe((data: any) => {
      this.users = data;
    });
  }

  deleteUser(id: string): void {
    this.userService.deleteUser(id).subscribe(() => {
      this.users = this.users.filter((user: any) => user._id !== id);
    });
  }
}


<div>
    <h2>User List</h2>
    <a routerLink="/users/create">Create User</a>
    <ul>
      <li *ngFor="let user of users">
        {{ user.name }} - {{ user.email }}
        <a routerLink="/users/edit/{{ user._id }}">Edit</a>
        <button (click)="deleteUser(user._id)">Delete</button>
      </li>
    </ul>
  </div>
